[package]
name = "isyswasfa-host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
futures = "0.3.30"
once_cell = "1.19.0"
wasmparser = "0.120.0"
wasmtime = { path = "../wasmtime/crates/wasmtime", features = ["component-model"] }
