package component:test;

interface baz {
  foo: func(s: string) -> string;
}

world round-trip {
  import wasi:clocks/monotonic-clock@0.2.0;
  import baz;
  export baz;
}

world service {
  import isyswasfa:io/pipe;
  export wasi:http/handler@0.3.0-draft-2024-02-14;
}

world middleware {
  include service;
  import wasi:http/handler@0.3.0-draft-2024-02-14;  
}
