[package]
name = "isyswasfa-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
by_address = "1.1.0"
futures = "0.3.30"
once_cell = "1.19.0"
wit-bindgen = { path = "../wit-bindgen/crates/guest-rust" }
